### ISSUE TITLE
Übergebene Werte

### ISSUE THREAD

**Issue by creditfairedv** [europace/kundenangaben-api#16]
Hallo,

ich habe Fragen zu den übergebenen Werten.

Kindergeld
Wird dieses automatisch berechnet wenn der Wert "kindergeldWirdBezogen" "wahr" ist und in die Ergebnisdarstelltung einbezogen? Ist der default Wert "falsch"?

Ratenkredite
Wie viele Kredite können hier übergeben werden? Bisher waren ja nur 3 möglich.

Viele Grüße

**Comment by s-gurevich** [comment]
Danke für deine Fragen!

Bei Kindergeld, wie den meisten Feldern auch, ist der Defaultwert NULL. Bei "true" wird das Kindergeld automatisch berechnet. Allerdings konfigurieren es die Produktanbieter, ob und zu welchem Teil das Kindergeld dann als Einnahme gilt.

Es ist max. ein Ratenkredit pro Kunde erlaubt. Da wir aktuell 2 Kunden pro Haushalt zulassen, können max. 2 Ratenkredite pro Haushalt übergeben werden. Wir werden die Dokumentation entsprechend ergänzen.

Ich hoffe, das hilft dir weiter.

**Comment by s-gurevich** [comment]
Habe die Antwort korrigiert. Bitte entschuldige das Durcheinander.
