### ISSUE TITLE
New BEX API

### ISSUE THREAD

**Issue by Pratheeka01** [europace/kundenangaben-api#18]
Quentions on request in new BEX API
- erbbaurecht is required request parameter in Kundenangaben->finanzierungsobjekt(Immobilie)-> erbbaurecht. Is it same as the erbbaurechtVorhanden in the older API (Vorgang->ErfassteDaten->finanzierungsObjekt->erbbaurecht)?

- For Kundenangaben->finanzierungsobjekt(Immobilie)-> Grundbuchangabe, is the below mapping ok
blattNummer(in the older API)->blatt
weitereAnmerkungen(in the older API)->anmerkungen
Also, what is amtsgericht?

Questions on the response in new BEX API.
- In the response, earlier we had VorgangMetadaten->empfaenger. Is it same as the new API VorgangMetadaten-> Betreuung-> kundenbetreuer?

**Comment by s-gurevich** [comment]
Thanks for your questions!

Erbbaurecht
- should not be a required paramter. We will fix that.
- erbbaurecht is the same as erbbaurechtVorhanden (Boolean)

Grundbuchangabe
- blattNummer is the same as blatt
- weitereAnmerkungen is the same as anmerkungen
- amtsgericht is a new field in the system. It means "district court" in English

Response
- VorgangMetadaten -> empfaenger is the KundenangabenImportResponse -> betreuung -> kundenbetreuer (We will add the reference in the documentation for more clarity)
