### ISSUE TITLE
New BEX API antragsteller

### ISSUE THREAD

**Issue by Pratheeka01** [europace/kundenangaben-api#19]
In the older API there were fields 
Vorgang->ErfassteDaten->antragsteller->**guetertrennungVereinbartWennVerheiratet**,
Vorgang->ErfassteDaten->antragsteller->**verheiratetmitWeiteremAntragstelle**. 
Vorgang->ErfassteDaten->antragsteller->zusatzAngaben ( containing the fields ingDiba", "sRating", "mhb", "bausparkassen)
Can you please let us know the right  mapping for these fields in the new API?

**Comment by s-gurevich** [comment]
`guetertrennungVereinbartWennVerheiratet`:
- This moved to `GetrenntLebend / Lebenspartnerschaft / Verheiratet `-> `guetertrennungVereinbart`

`verheiratetmitWeiteremAntragsteller`:
- This is not relevant anymore.

`zusatzangaben`:
- All `zusatzangaben` (multiple places) are currently missing and will be added after the rest of the API is stable. 

Also, please consider that the current state of the model is a draft. Changes still take place.
