### ISSUE TITLE
New BEX API (Haushalt)

### ISSUE THREAD

**Issue by Pratheeka01** [europace/kundenangaben-api#20]
We are having issues in finding the right mapping of some of the fields of the old API in the new API.

- Haushalt->einnahmenAusgabenVermoegenVerbindlichkeiten(HaushaltsPositionen)->ausgabenSonstigeMonatlich

- Haushalt->einnahmenAusgabenVermoegenVerbindlichkeiten(HaushaltsPositionen)-> Bausparvertrag -> 
   vermoegensVerwendung

- Haushalt->einnahmenAusgabenVermoegenVerbindlichkeiten(HaushaltsPositionen)->unterhaltsVerpflichtungMonatlich

- Haushalt->einnahmenAusgabenVermoegenVerbindlichkeiten(HaushaltsPositionen)-> 
   variableEinkuenfteMonatlich,verbindlichkeitSonstige

- Haushalt->einnahmenAusgabenVermoegenVerbindlichkeiten(HaushaltsPositionen)->unbefristeteZusatzRenteMonatlich

- Haushalt->einnahmenAusgabenVermoegenVerbindlichkeiten(HaushaltsPositionen)-> 
   ehegattenUnterhaltEinnahmenMonatlich

- Haushalt->einnahmenAusgabenVermoegenVerbindlichkeiten(HaushaltsPositionen)->einnahmenSonstigeMonatlich

-  Haushalt->einnahmenAusgabenVermoegenVerbindlichkeiten(HaushaltsPositionen)-> 
    privateKrankenversicherungBeitragMonatlich, versicherungsAusgabenSonstigeMonatlich, Wertpapiere
    Wertpapiere - this object seems to be removed. Is it not required anymore.

- Haushalt->einnahmenAusgabenVermoegenVerbindlichkeiten(HaushaltsPositionen)->bankUndSparguthaben (Old API), the fields of BankUndSparguthaben are changed. zinsertragJaehrlich is the only same one?

- Is the mapping for Kundenangaben->haushalte-> finanzielleSituation-> Haushaltsvermoegen->sparplaene-> 
  AufloesungAlsVerwendung->maximalEinzusetzenderBetrag in the new API is same as the Vorgang->erfassteDaten-> 
  haushalt->HaushaltsPositionen->sparplaene->maximalAufzuloesenderWert in the old one?

- We see a lot of objects having the kommentar field. What is the importance of this field?

- Kundenangaben->haushalte-> finanzielleSituation-> Haushaltsvermoegen->BausparvertragAlsVermoegen->jahresentgelt 
   is the new field in the new API? If yes, what does this field signify?

- Kundenangaben->haushalte-> finanzielleSituation-> Haushaltsvermoegen->BausparvertragAlsVermoegen-> 
   Bausparvertragsdetails->**vertragsbeginn, zuteilungsdatum**? These fields are new?

**Comment by s-gurevich** [comment]
Haushalt->einnahmenAusgabenVermoegenVerbindlichkeiten(HaushaltsPositionen)->ausgabenSonstigeMonatlich
- Haushalt -> finanzielleSituation -> ausgaben (Haushaltsausgaben) -> summeSonstigerAusgabenMonatlich

Haushalt->einnahmenAusgabenVermoegenVerbindlichkeiten(HaushaltsPositionen)-> Bausparvertrag -> vermoegensVerwendung
- Haushalt -> finanzielleSituation -> vermoegen (Haushaltsvermoegen) -> BausparvertragAlsVermoegen -> verwendung (AufloesungAlsVerwendung or AbtretenAlsVerwendung)

Haushalt->einnahmenAusgabenVermoegenVerbindlichkeiten(HaushaltsPositionen)->unterhaltsVerpflichtungMonatlich
- Haushalt -> finanzielleSituation -> ausgaben (Haushaltsausgaben) -> unterhaltsverpflichtungenMonatlich

Haushalt->einnahmenAusgabenVermoegenVerbindlichkeiten(HaushaltsPositionen)->variableEinkuenfteMonatlich,verbindlichkeitSonstige
- Haushalt -> finanzielleSituation -> einnahmen (Haushaltseinnahmen) -> summeVariablerEinkuenfteMonatlich
- Haushalt -> finanzielleSituation -> verbindlichkeiten (Haushaltsverbindlichkeiten) -> sonstigeVerbindlichkeit

Haushalt->einnahmenAusgabenVermoegenVerbindlichkeiten(HaushaltsPositionen)->unbefristeteZusatzRenteMonatlich
- Haushalt -> finanzielleSituation -> einnahmen (Haushaltseinnahmen) -> summeUnbefristeteZusatzrentenMonatlich

Haushalt->einnahmenAusgabenVermoegenVerbindlichkeiten(HaushaltsPositionen)->ehegattenUnterhaltEinnahmenMonatlich
- Haushalt -> finanzielleSituation -> einnahmen (Haushaltseinnahmen) -> summeEhegattenunterhalt

Haushalt->einnahmenAusgabenVermoegenVerbindlichkeiten(HaushaltsPositionen)->einnahmenSonstigeMonatlich
- Haushalt -> finanzielleSituation -> einnahmen (Haushaltseinnahmen) -> summeSonstigeEinnahmenMonatlich

Haushalt->einnahmenAusgabenVermoegenVerbindlichkeiten(HaushaltsPositionen)->
    privateKrankenversicherungBeitragMonatlich, versicherungsAusgabenSonstigeMonatlich, Wertpapiere
    Wertpapiere - this object seems to be removed. Is it not required anymore.
- Haushalt -> finanzielleSituation -> ausgaben (Haushaltsausgaben) -> summePrivaterKrankenversicherungenMonatlich
- Haushalt -> finanzielleSituation -> ausgaben (Haushaltsausgaben) -> summeSonstigerVersicherungsausgabenMonatlich
- Haushalt -> finanzielleSituation -> einnahmen (Haushaltseinnahmen) -> summeEinkuenfteAusKapitalvermoegen [for Wertpapiere -> dividendenJaehrlich]
- Haushalt -> finanzielleSituation -> vermoegen (Haushaltsvermoegen) -> summeDepotvermoegen (Depotvermoegen) ->  depotwert [for Wertpapiere -> gesamtwert] and verwendung (AufloesungAlsVerwendung) [for Wertpapiere -> maximalAufzuloesenderWert]

Haushalt->einnahmenAusgabenVermoegenVerbindlichkeiten(HaushaltsPositionen)->bankUndSparguthaben (Old API), the fields of BankUndSparguthaben are changed. zinsertragJaehrlich is the only same one?
- BankUndSparguthaben -> guthaben [for bankUndSparguthabenGesamt]
- BankUndSparguthaben -> zinsertragJaehrlich [for zinsertragJaehrlich] 
- BankUndSparguthaben -> verwendung (AufloesungAlsVerwendung) -> maximalEinzusetzenderBetrag (with aufloesen = true) [for maximalAufzuloesendesBankUndSparguthaben]

Is the mapping for Kundenangaben->haushalte-> finanzielleSituation-> Haushaltsvermoegen->sparplaene->
    AufloesungAlsVerwendung->maximalEinzusetzenderBetrag in the new API is same as the Vorgang->erfassteDaten->
    haushalt->HaushaltsPositionen->sparplaene->maximalAufzuloesenderWert in the old one?
- Yes 

We see a lot of objects having the kommentar field. What is the importance of this field?
- Kommentar means 'comment' in English. Hence, if the financial advisor wants to add a free text comment, they can use those fields

Kundenangaben->haushalte-> finanzielleSituation-> Haushaltsvermoegen->BausparvertragAlsVermoegen->jahresentgelt
    is the new field in the new API? If yes, what does this field signify?
- Jahr means year in English, Entgelt means "fee". It is the yearly fee.

Kundenangaben->haushalte-> finanzielleSituation-> Haushaltsvermoegen->BausparvertragAlsVermoegen->
    Bausparvertragsdetails->vertragsbeginn, zuteilungsdatum? These fields are new?
- Regarding the BEX-API those fields are new, but they were available in the BaufiSmart system (and UI) before.
- Vertragsbeginn = Start of the contract
- Zuteilungsdatum = Grant date

Furthermore, we would kindly ask you to request a German speaking colleague from your company to assist you understanding the API.

**Comment by Pratheeka01** [comment]
Thanks for the clarification
