### ISSUE TITLE
fehlende Felder und API Bereitstellung

### ISSUE THREAD

**Issue by ginheb** [europace/kundenangaben-api#25]
Hi, 

ich möchte die neue API anprogrammieren. Folgende Fragen und Unklarheiten stellen sich da mir: 

Fragen:
- unsere Kundennummer ist im Feld externeKundenId richtig aufgehoben, oder?

Unklarheiten (Offen):
Wir haben verschiedene Fach-Felder, für die ich kein entsprchendes Feld im yaml finde: 
- Geschlecht (wird das nicht benötigt? Leitet Ihr das aus der Anrede ab?)
- Bonitätsklasse (fachlich abgestimmt ist offenbar eine Mitgabe der Bonitätsklasse, die im Rahmen der europace-Verarbeitung prozessualen Einfluss haben soll. Wo kann ich diese unterbringen)
- Freie Felder zur Durchleitung von Informationen (bspw. CRM-ID, die bei Anlage mitgegeben wird und bei späterer Abholung der Daten zurückgeliefert werden kann. Damit kann eine Folgeverarbeitung in abweichenden Systemen stark vereinfacht werden. Diese Daten haben keine Einfluss auf den Verarbeitungsprozess von europace)

Wann ist mit einem öffentlichen Zugang (DEV) der API zu rechnen?

Dank und Gruss

**Comment by s-gurevich** [comment]
Hi,

danke für deine Fragen!

- _Eure Kundennummer:_ Ist im Feld externeKundenId richtig aufgehoben.
- _Geschlecht:_ Wird in BaufiSmart nicht gesondert erfasst. Bitte die Anrede entsprechend setzen.
- _Bonitätsklasse:_ Ist noch nicht abgebildet. Die Umsetzung ist geplant und wird im nächsten Schritt erarbeitet. 
- _Freie Felder zur Durchleitung von Informationen:_ Die API gibt die Vorgangs-ID zurück. Bitte speichert die Beziehung der Vorgang-ID zu euren internen Daten in euren Systemen. Es ist möglich, eure VorgangId bei uns zu speichern. In den Metadaten heißt das Feld externeReferenzId. Da es doch zu Missverständnissen kommen könnte, werden wir das Feld zu externeVorgangsId umbenennen. Update folgt.
- _Die API_ befindet sich in Entwicklung. Da der aktuelle Stand des Modells aber bereits veröffentlicht ist und nur kleine Änderungen zu erwarten sind, können unsere Partner bereits mit dem Mapping des eigenen Modells auf das Kundenangaben-Modell beginnen.

**Comment by ginheb** [comment]
Hi, 
zu einem Punkt habe ich noch eine Bemerkung.

- freie Felder zur Durchleitung von Informationen: externeReferenzId in den Metadaten-Bereich hatte ich gesehen. Die Durchleitung der VorgangsId mag auch teilweise für die beteiligten Systeme (Auftrag, Ergebnis-Verarbeitung, Monitoring, usw.) reichen. Häufig arbeiten aber nicht alle Systeme komplett Vorgangs-bezogen (Altsysteme u.Ä.)  und es ist einfacher für diese Systeme Daten aus dem Auftrag durchzureichen. Damit würde man eine größere Flexibilität erreichen.  

Da die API neu ist, sollte man so eine Flexibilität zumindest diskutieren. 

Gruß

**Comment by acodingsquirrel** [comment]
Die neue API empfängt Daten aus einem bestehendem System und überträgt die Informationen nach BaufiSmart.
Wir unterstützen die Synchronität mit Systemen außerhalb von BaufiSmart auch dadurch, das ihr eine externe Vorgangs-ID hinterlegen könnt.
BaufiSmart wird sich nach unserer heutigen Ansicht nicht in die Richtung weiterentwickeln Informationen durchzuleiten.
Dafür geben wir euch mit den externen Referenzen unterstützende Werkzeuge in die Hand.
