### ISSUE TITLE
yaml swagger Fehler

### ISSUE THREAD

**Issue by ginheb** [europace/kundenangaben-api#28]
swagger meldet einen Referenzfehler im yaml: 

Semantic error at paths./kundenangaben.post.parameters.1.$ref
$refs must reference a valid location in the document
Jump to line 35

Zur Info.

**Comment by roamingthings** [comment]
Ich habe die Datei manuell, mit dem [OpenAPI-Generator](https://github.com/OpenAPITools/openapi-generator) und dem [Swagger Codegen (V3)](https://github.com/swagger-api/swagger-codegen) geprüft und konnte keine Fehler feststellen.

In der Betreffenden Zeile wird der `TraceId` Header referenziert. Möglicherweise wird dies nicht von allen Generatoren unterstützt.

Wir werden diese Parameter auf eine andere Art definieren, die hoffentlich von mehr Generatoren verarbeitet werden kann.

**Comment by ginheb** [comment]
jetzt geht es
