### ISSUE TITLE
Land Ausprägungsmenge 

### ISSUE THREAD

**Issue by ginheb** [europace/kundenangaben-api#29]
gibt es für das Feld "haushalte[]/kunden[]/personendaten/staatsangehoerigkeit/land" eine bestimmte Ausprägungsmenge?

**Comment by s-gurevich** [comment]
Danke für die Frage!

Das Land muss ein valider ISO 3166-1 alpha-2 Code sein.

Wir werden die Dokumentation entsprechend ergänzen.
