### ISSUE TITLE
hinweise/warning/error Feld in response

### ISSUE THREAD

**Issue by ginheb** [europace/kundenangaben-api#30]
wird es kein Feld für Hinweise/Warnings in der Response geben, die im Positivfall auftreten könnten? Wie werden fachliche Fehler (bspw. Land falsch) gemeldet?

**Comment by ginheb** [comment]
oder wird sowas als http-status 400 geliefert mit dem 'message' Feld?

**Comment by ginheb** [comment]
bei Status 400 kommt in error=Bar Request und in path=/kundenangaben

Es ist nicht richtig gut erkennbar an welcher Stelle des Requests (json) was genau falsch ist. Sehr hilfreich wäre eine Angabe auf das 1. fehlerhafte oder alle fehlerhaften Felder.

**Comment by s-gurevich** [comment]
Das Modell wird beim Erhalt validiert werden. Als Antwort wird zurückgegeben, was an dem Modell nicht stimmt. Das ist jedoch noch in Arbeit. Wir sagen hier Bescheid, sobald man die Validierung des Modells testen kann.

**Comment by s-gurevich** [comment]
Ab jetzt ist die Validierung online und kann gern getestet werden.

Wenn im Body zum Beispiel in einem Haushalt mehr als 2 Kunden geschickt werden, gibt es diese Antwort:

```
{
    "type": "https://api.europace.de/problem/constraint-violation",
    "status": 400,
    "violations": [
        {
            "field": "haushalte[0].kunden",
            "message": "size must be between 0 and 2"
        }
    ],
    "title": "Constraint Violation"
}
```

**Comment by ginheb** [comment]
funktioniert!
