### ISSUE TITLE
externeVorgangsId in andere APIs durchgeleitet?

### ISSUE THREAD

**Issue by ginheb** [europace/kundenangaben-api#32]
Hi, 

wird das Feld externeVorgangsId auch in die "Anträge Lesen" API aufgenommen, damit diese Information durchgeleitet wird? 

Bei uns ist das beauftragende System abweichend vom später verarbeitenden System, wenn die Daten zurückkommen. Eine Durchleitung "freier Kunden-Felder" habt ihr ja leider abgelehnt. 

Zumindest die Weitergabe der VorgangsId wäre dann aber nötig.

**Comment by s-gurevich** [comment]
Hi,

die externeVorgangsId wird in der Anträge auslesen API als VorgangsReferenz herausgegeben.
