### ISSUE TITLE
fehlendes Feld für Konto

### ISSUE THREAD

**Issue by ginheb** [europace/kundenangaben-api#33]
Hi, 

abgestimmt ist offenbar auch die Annahme einer KtoNr. Für diese finde ich im aktuellen Modell noch kein aufnehmendes Feld. Kommt das noch?

**Comment by s-gurevich** [comment]
Hi,

die Kontonummer wird als IBAN hier erfasst: https://htmlpreview.github.io/?https://raw.githubusercontent.com/europace/kundenangaben-api/master/reference/index.html#_Bankverbindung

**Comment by ginheb** [comment]
habe ich übersehen, sorry
