### ISSUE TITLE
wenn ich überhaupt keine Felder des scope baufinanzierung habe, bekomme ich aber kein Problem, oder?

### ISSUE THREAD

**Issue by ginheb** [europace/kundenangaben-api#39]
wenn ich überhaupt keine Felder des scope baufinanzierung habe, bekomme ich aber kein Problem, oder?

_Originally posted by @ginheb in https://github.com/europace/kundenangaben-api/pull/38#issuecomment-723963530_

**Comment by roamingthings** [comment]
Hi,

ich bin mir nicht ganz sicher, was mit "Felder" gemeint ist.

Für den Aufruf der API werden die beiden Scopes "baufinanzierung:echtgeschaeft" (kann beim Test-Modus entfallen) und "baufinanzierung:vorgang:schreiben" benötigt. Andernfalls wird der Request mit FORBIDDEN zurückgewiesen.

**Comment by ginheb** [comment]
hat sich erledigt. ich hab´s falsch verstanden

danke
