### ISSUE TITLE
Credentials false

### ISSUE THREAD

**Issue by 4yourfinance** [europace/kundenangaben-api#40]
Tilo, hello. I try to send a request to  https://api.europace.de/auth/token to get the access token, and I got the error:
"Client authentication failed: Client id unknown \/ deactivated or client secret invalid \/ expired"

I use this data:
ID: TNK48 - like as Client_ID.
ApiKey: d0dewkdwlx7vitdms3.... - Client-Secret

And I send them in the basic authorization header.

**Comment by roamingthings** [comment]
Hi!
the ID you're using is not the client_id required for authentication.
The Client ID required for API authentication looks like `VJATKDIGHEN...`

**Comment by FellowNik** [comment]
Yes, I try to get it to send a request to API. I use https://github.com/europace/authorization-api documentation. As I understand it, I need to get an Acces_token to send it in the Authorization header for further requests, right? 
Please tell, where I can get Client_ID and Client_Secret for this?

**Comment by 4yourfinance** [comment]
Please can you give us an answer? Client_ID and Client_Secret required for API authentication, where we can get them?

**Comment by MikeKrueger75** [comment]
> Please can you give us an answer? Client_ID and Client_Secret required for API authentication, where we can get them?

https://docs.api.europace.de/baufinanzierung/authentifizierung/#wie-bekomme-ich-einen-client-registriert
