### ISSUE TITLE
Authorization header (Credential, Signature, SignedHeaders, X-Amz-Date). 

### ISSUE THREAD

**Issue by 4yourfinance** [europace/kundenangaben-api#44]
Hello! We got access token by documentation:
https://github.com/europace/authorization-api

And by https://baufinanzierung.api.europace.de from the YAML file:
https://github.com/europace/kundenangaben-api/blob/master/api-docs.yaml

We sent a request to https://baufinanzierung.api.europace.de by the GET method:

_Headers:_
    ` "Authorization": [access token got with https://api.europace.de/auth/access-token]`
_Body:_
```
   "kundenangaben": {..},
   "importMetadaten": {
        "datenkontext": "TEST_MODUES"
   }
```

And got  **403** HTTP response code and this error:

`{"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header...`

When we send data to **kundenangaben**
https://baufinanzierung.api.europace.de/kundenangaben

We got the **401** response code, and no error more. 

Please tell, where we can view information about these headers?  How do we need to generate these?
Or do we something wrong?

**Comment by s-gurevich** [comment]
Hi, few things I see in your question:
- "datenkontext": "TEST_MODUES" is supposed to be `TEST_MODUS`
- the operation is POST, not GET
- Did you add the "Bearer" before the access token?: `Authorization: Bearer [Access_Token]`
Please try again and let us know, if it worked.

**Comment by 4yourfinance** [comment]
Thank you! It is worked.
