### ISSUE TITLE
Cannot deserialize into .. at line: 1

### ISSUE THREAD

**Issue by 4yourfinance** [europace/kundenangaben-api#45]
Hi! 
We try to send below data with **application/json** **Content-Type** header:

```
"{
    "kundenangaben":
    {
        "finanzierungsbedarf":
        {
            "finanzierungsbausteine":
            {
                "darlehensbetrag":"25.1"
            }
        },
        "Finanzierungsobjekt": {
            "adresse": {
                "strasse": "test_strasse1",
                "hausnummer": "test_hausnummer1",
                "plz": "test_plz1",
                "ort": "test_ort1"
            }
        }
    },
    "importMetadaten": {
        "datenkontext":"TEST_MODUS"
    }
}"
```
_(in the UTF-8 encoding)_

And got the error:

`Cannot deserialize into 'kundenangaben.finanzierungsbedarf.finanzierungsbausteine' at line: 1, column: 67`

Please tell, what is wrong?

P.S 
-if we send no JSON or empty string we get the error "**The request is not readable**"
-we tried to delete the null byte from the right JSON string, but it is no help

_request date: Mon, 23 Nov 2020 11:39:11 GMT_

**Comment by s-gurevich** [comment]
`finanzierungsbausteine` is a list, not an object. Please refer to the documentation: https://htmlpreview.github.io/?https://raw.githubusercontent.com/europace/kundenangaben-api/master/reference/index.html#_Finanzierungsbedarf
Also the list contains objects of different types (Annuitaetendarlehen, Bauspardarlehen, Forwarddarlehen, KfwDarlehen, Privatdarlehen, VariablesDarlehen, Zwischenfinanzierung). All of them have a mandatory field `@type`.
Furthermore, `Finanzierungsobjekt` needs to start with a small f.

**Comment by s-gurevich** [comment]
> if we send no JSON or empty string we get the error "**The request is not readable**"

This is correct behaviour. The endpoint expects an object in the body. Body cannot be empty or a string, but must be an object with mandatory fields. See https://htmlpreview.github.io/?https://raw.githubusercontent.com/europace/kundenangaben-api/master/reference/index.html#_ImportKundenangabenRequest

**Comment by roamingthings** [comment]
To give an example demonstrating how to specify _Finanzierungsbausteine_ please take a look at the following snippet:
```json
{
    "kundenangaben": {
        "finanzierungsbedarf": {
            "finanzierungsbausteine": [
                {
                    "@type": "ANNUITAETENDARLEHEN",
                    "referenzId": "Referenz Annu",
                    "darlehensbetrag": 234567.8,
                    "annuitaetendetails": {
                        "zinsbindungInJahren": 10,
                        "tilgungswunsch": {
                            "@type": "RATE",
                            "rate": 1567.9,
                            "tilgungsbeginn": "2020-09-20"
                        },
                        "sondertilgungJaehrlich": 5.8,
                        "auszahlungszeitpunkt": "2021-07-19"
                    },
                    ...
                }
            ],
            ...
        },
        ...
    },
    ...
}
```

**Comment by 4yourfinance** [comment]
Thank you for your answers! 

Now the  'finanzierungsbausteine' is an array, also subelements have a mandatory @type field. 
And It looks correct, but we get other error:

_Cannot deserialize into 'kundenangaben' at line: 1, column: 30_

We sending this data::

_full JSON to view with the browser console:_
`{"kundenangaben":{"finanzierungsbedarf":{"finanzierungsbausteine":[{"@type":"ANNUITAETENDARLEHEN","referenzId":"Referenz Annu","darlehensbetrag":234567.8,"annuitaetendetails":{"zinsbindungInJahren":10,"tilgungswunsch":{"@type":"RATE","rate":1567.9,"tilgungsbeginn":"2020-09-20"},"sondertilgungJaehrlich":5.8,"auszahlungszeitpunkt":"2021-07-19"}}]}},"importMetadaten":{"datenkontext":"TEST_MODUS"}}`

_as PHP array, before calling php json_encode function:_
```
Array
(
    [kundenangaben] => Array
        (
            [finanzierungsbedarf] => Array
                (
                    [finanzierungsbausteine] => Array
                        (
                            [0] => Array
                                (
                                    [@type] => ANNUITAETENDARLEHEN
                                    [referenzId] => Referenz Annu
                                    [darlehensbetrag] => 234567.8
                                    [annuitaetendetails] => Array
                                        (
                                            [zinsbindungInJahren] => 10
                                            [tilgungswunsch] => Array
                                                (
                                                    [@type] => RATE
                                                    [rate] => 1567.9
                                                    [tilgungsbeginn] => 2020-09-20
                                                )

                                            [sondertilgungJaehrlich] => 5.8
                                            [auszahlungszeitpunkt] => 2021-07-19
                                        )
                                )
                        )
                )
     )
    [importMetadaten] => Array
        (
            [datenkontext] => TEST_MODUS
        )
)
```

Please suggest where the error? What are we missed?

**Comment by acodingsquirrel** [comment]
Hallo 4yourfinance,
super, das du dich so aktiv für unsere Schnittstelle interessierst.
Wir haben uns gerne die Zeit genommen dir mehrere detaillierte Nachfragen zu beantworten. Bei ein oder zwei Nachfragen unterstützen wir dich auch.
Über GitHub-Issues freuen wir uns über Feedback zur API. Wir bieten keinen Eingangskanal, um beim Implementieren der API zu unterstützen. Es ist mit den Angaben in GitHub möglich die API an die eigenen Systeme anzuschließen.
Die API zu implementieren sehen wir als Aufgabe unserer Vertriebspartner. Wir würden dich bitten mit deiner eigenen Expertise die Fragen zu beantworten oder in deiner Organisation nach Unterstützung zu Fragen.
Viele liebe Grüße
