### ISSUE TITLE
beta2 yaml hat Fehler

### ISSUE THREAD

**Issue by ginheb** [europace/kundenangaben-api#48]
Hi, 

swagger-Editor liefert mit der aktuellen yaml (beta2) folgende Meldungen: 
Errors
Hide
 
Structural error at components.responses.BadRequest.headers.X-TraceId
should have either a `schema` or `content` property
Jump to line 4450
Structural error at components.responses.Forbidden.headers.X-TraceId
should have either a `schema` or `content` property
Jump to line 4459
Structural error at components.responses.Unauthorized.headers.WWW-Authenticate
should have either a `schema` or `content` property
Jump to line 4468
Structural error at components.responses.ServiceNotAvailable.headers.X-TraceId
should have either a `schema` or `content` property
Jump to line 4474
Structural error at components.parameters.tracingIdParam
should have either a `schema` or `content` property
Jump to line 4481
Structural error at components.headers.tracingIdHeader
should have either a `schema` or `content` property
Jump to line 4486

**Comment by roamingthings** [comment]
Hi!

Vielen Dank für den Hinweis. Wir werden die Spezifikation korrigieren.
