### ISSUE TITLE
Glückwunsch zur Beta

### ISSUE THREAD

**Issue by tilomlr** [europace/kundenangaben-api#53]
Hallo Europace-Team,

ich habe gesehen, dass ihr wieder einen Meilenstein erreicht habt, die neue Beta-Version.
Deshalb für mich natürlich die spannende Frage: Könnt ihr schon abschätzen wann das Finale Release der v1.0 sein wird?

Falls nicht, könnt ihr uns vielleicht sagen, ob es noch größere Änderungen geben wird?

VG Tilo

**Comment by leifhanack** [comment]
Danke der Nachfrage, Tilo. 

Hast du schon gesehen, deine Frage haben wir prompt mit dem Release 1.0.0. beantwortet ;). Die API ist inkl. Zusatzangaben definiert. Größere Änderungen sind aktuell nicht vorgesehen. Erweiterung können sich natürlich ergeben.

Eine offizielle Kommunikation dazu per Newsletter und im direkten Austausch mit unseren Partnern ist ebenso in Planung, um die notwendige Migration anzustoßen.

Danke dir, Gruß Leif

**Comment by tilomlr** [comment]
Hallo Leif,

ich bin baff 😮, das nenn ich mal eine klasse Antwort :-). Ihr seid Spitze!

VG Tilo
